apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websocket-service-ingress
  namespace: default
  annotations:
  
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: websocket-service
                port:
                  number: 80
