namespace: default

replicaCount: 1

app:
  name: websocket

image:
  repository: oshall95/websocket-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "128Mi"

autoscaling:
  enabled: false # Change to true if you want HPA to be enabled
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/websocket-services: "websocket-service"
  hosts:
    - host: websocket.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: websocket-service
            servicePort: 8000

serviceAccount:
  create: false  # Add this line to disable service account creation
  name: "websocket-service-account"  # Keep your service account name here

imagePullSecrets:
  - name: dockerhub-secret
