name: Deploy to Azure Kubernetes Service

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Kubernetes Context
      run: az aks get-credentials --resource-group my-new-resource-group --name my-new-cluster --overwrite-existing

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/hpa.yaml
        kubectl apply -f kubernetes/ingress.yaml
