name: Deploy to Azure Kubernetes Service

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group devops-central-india --name sherkety-cluster-central-india --overwrite-existing

      - name: Deploy to Kubernetes using Helm
        run: |
          helm upgrade --install websocket-service ./kubernetes/helm \
            --set image.repository=oshall95/fastapi-websocket \
            --set image.tag=latest
