name: Deploy to Azure Kubernetes Service

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Kubernetes Context
      run: |
        # Fetch the Kubernetes credentials for the cluster
        az aks get-credentials --resource-group my-new-resource-group --name new-cluster-2 --overwrite-existing
        # Verify the context is set correctly
        kubectl config get-contexts
        kubectl config use-context new-cluster-2

    - name: Deploy to Kubernetes
      run: |
        # Apply Kubernetes resources using Helm
        helm upgrade --install websocket-service ./helm --namespace default --values ./helm/values.yaml
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/hpa.yaml
        kubectl apply -f kubernetes/ingress.yaml
        kubectl apply -f kubernetes/prometheus-service.yaml
